from __future__ import annotations

import re


FORMATS = {"sigma", "yara", "kql", "spl", "eql"}


def generate_detection(title: str, technique_id: str, format: str, telemetry: list[str]) -> str:
    fmt = format.lower()
    if fmt not in FORMATS:
        raise ValueError(f"Unsupported format: {format}")
    telemetry = telemetry or ["process_creation"]
    needle = technique_id.replace(".", "_").lower()
    if fmt == "sigma":
        return "\n".join([
            f"title: {title}", f"id: generated-{needle}", "status: experimental",
            "description: Analyst-review skeleton generated by AdversaryGraph",
            f"tags:\n  - attack.{needle}", f"logsource:\n  category: {telemetry[0]}",
            "detection:\n  selection:\n    CommandLine|contains: REPLACE_WITH_BEHAVIOR\n  condition: selection",
            "falsepositives:\n  - Validate in the target environment", "level: medium",
        ])
    if fmt == "yara":
        rule_name = re.sub(r"[^A-Za-z0-9_]", "_", title).strip("_") or f"adversarygraph_{needle}"
        if not rule_name[0].isalpha() and rule_name[0] != "_":
            rule_name = f"rule_{rule_name}"
        return "\n".join([
            f"rule {rule_name}",
            "{",
            "  meta:",
            f'    description = "Analyst-review skeleton for {technique_id}"',
            '    author = "AdversaryGraph"',
            f'    attack = "{technique_id}"',
            "  strings:",
            '    $placeholder = "REPLACE_WITH_BEHAVIOR" ascii wide nocase',
            "  condition:",
            "    $placeholder",
            "}",
        ])
    field = "CommandLine"
    query = f'{field} contains "REPLACE_WITH_BEHAVIOR"'
    if fmt == "spl":
        return f'index=* "{technique_id}" | search {field}="*REPLACE_WITH_BEHAVIOR*"'
    if fmt == "eql":
        return 'process where process.command_line : "*REPLACE_WITH_BEHAVIOR*"'
    return query


def validate_detection(format: str, content: str) -> dict:
    fmt = format.lower()
    errors: list[str] = []
    warnings: list[str] = []
    if fmt not in FORMATS:
        errors.append(f"Unsupported format: {format}")
    if not content.strip():
        errors.append("Rule content is empty")
    if "REPLACE_WITH_BEHAVIOR" in content:
        warnings.append("Template placeholder must be replaced before production")
    if fmt == "sigma":
        for required in ("title:", "logsource:", "detection:", "condition:"):
            if required not in content:
                errors.append(f"Missing Sigma field: {required}")
    if fmt == "yara":
        if not re.search(r"(?m)^\s*(?:private\s+|global\s+)*rule\s+[A-Za-z0-9_:-]+", content):
            errors.append("Missing YARA rule declaration")
        if "condition:" not in content:
            errors.append("Missing YARA condition block")
    if fmt in {"kql", "eql"} and not re.search(r"\b(contains|where|has|:)\b", content, re.I):
        warnings.append("Query has no recognizable filter expression")
    return {"valid": not errors, "errors": errors, "warnings": warnings, "format": fmt}
